#!/bin/sh
set -eu

CONFIG="Release-Dev"

# value=$(cat ../secret)
# git pull "https://mungert69:$value@github.com/Mungert69/NetworkMonitorSearch"

TAG="$(sed -n 's/.*<ContainerImageTag>\(.*\)<\/ContainerImageTag>.*/\1/p' NetworkMonitorSearch.csproj | head -n1)"
[ -n "${TAG:-}" ] || TAG="latest"
REPO="$(
  awk -v cfg="$CONFIG" '
    /<PropertyGroup/ && /Condition=/ {
      inpg = ($0 ~ ("\\x27\\$\\(Configuration\\)\\x27[[:space:]]*==[[:space:]]*\\x27" cfg "\\x27"))
    }
    inpg && /<ContainerRepository>/ {
      line=$0
      sub(/.*<ContainerRepository>/,"",line)
      sub(/<\/ContainerRepository>.*/,"",line)
      print line
      exit
    }
    /<\/PropertyGroup>/ { inpg=0 }
  ' NetworkMonitorSearch.csproj
)"
[ -n "${REPO:-}" ] || REPO="mungert/networkmonitorsearch-dev"

echo "Publishing multi-arch container: $REPO:$TAG ($CONFIG)"

dotnet test --nologo || true

dotnet publish NetworkMonitorSearch.csproj \
  -c "$CONFIG" \
  -t:PublishContainer

