#!/bin/sh
value=`cat ../secret`
git pull https://mungert69:$value@github.com/Mungert69/NetworkMonitorService
dotnet publish -m --os linux --arch x64 -p:PublishProfile=DefaultContainer -c Release-Dev --self-contained true 
